@startuml Memo app

!define TRANSACTION_MARK_COLOR FFAA00

package "Memo app" as memo_app {

  entity "メモ" as memo_detail <<M,MASTER_MARK_COLOR>> {
      タイトル
      内容
      --
      新規作成
      タイトル変更
      内容変更
      削除
  }
}

@enduml
